import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        'secondary-container': '#ffc659',
        'primary-fixed-dim': '#b2c7ef',
        'surface-container-high': '#dee8ff',
        'inverse-on-surface': '#ebf1ff',
        'on-surface-variant': '#44474e',
        'on-primary-container': '#768baf',
        'tertiary-fixed': '#e1e3e4',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#271900',
        'secondary-fixed': '#ffdea8',
        'error-container': '#ffdad6',
        'surface-bright': '#f9f9ff',
        'tertiary-container': '#202324',
        'on-background': '#111c2c',
        'on-tertiary-container': '#888a8b',
        'surface': '#f9f9ff',
        'surface-container': '#e7eeff',
        'on-primary-fixed': '#021c3a',
        'on-tertiary-fixed': '#191c1d',
        'on-secondary': '#ffffff',
        'surface-tint': '#4a5f81',
        'primary': '#000d22',
        'secondary': '#7c5800',
        'on-primary-fixed-variant': '#324768',
        'inverse-primary': '#b2c7ef',
        'outline-variant': '#c4c6cf',
        'surface-container-highest': '#d8e3fa',
        'error': '#ba1a1a',
        'on-secondary-container': '#745200',
        'outline': '#74777e',
        'tertiary-fixed-dim': '#c5c7c8',
        'on-surface': '#111c2c',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#f5bd52',
        'on-secondary-fixed-variant': '#5e4200',
        'surface-container-low': '#f0f3ff',
        'on-error-container': '#93000a',
        'background': '#f9f9ff',
        'surface-dim': '#cfdaf1',
        'tertiary': '#0a0d0e',
        'inverse-surface': '#263142',
        'primary-fixed': '#d5e3ff',
        'primary-container': '#0a2342',
        'on-tertiary-fixed-variant': '#454748',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#d8e3fa',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'section-padding-desktop': '120px',
        'max-width': '1280px',
        'gutter': '24px',
        'section-padding-mobile': '60px',
        'base': '8px',
      },
      fontFamily: {
        'headline-sm': ['Playfair Display', 'serif'],
        'label-md': ['Inter', 'sans-serif'],
        'caption': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'display-lg': ['Playfair Display', 'serif'],
        'display-lg-mobile': ['Playfair Display', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'caption': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      maxWidth: {
        'max-width': '1280px',
      },
    },
  },
  plugins: [forms, containerQueries],
};
